In [1]:
!pip install numpy

Requirement already satisfied: numpy in c:\users\gupta\anaconda3\lib\site-packages (1.19.2)

In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\gupta\anaconda3\lib\site-packages (1.1.3)
Requirement already satisfied: pytz>=2017.2 in c:\users\gupta\anaconda3\lib\site-packages (from pandas) (2020.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\gupta\anaconda3\lib\site-packages (from pandas) (2.8.1)
Requirement already satisfied: numpy>=1.15.4 in c:\users\gupta\anaconda3\lib\site-packages (from pandas) (1.19.2)
Requirement already satisfied: six>=1.5 in c:\users\gupta\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [3]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df=pd.read_csv(r"C:\Users\gupta\Downloads\bitcoin.csv")

In [6]:
df.head(5)

        Date        Price
0  5/23/2019  7881.846680
1  5/24/2019  7987.371582
2  5/25/2019  8052.543945
3  5/26/2019  8673.215820
4  5/27/2019  8805.778320

In [8]:
df.values

array([['5/23/2019', 7881.84668],
       ['5/24/2019', 7987.371581999999],
       ['5/25/2019', 8052.543945],
       ['5/26/2019', 8673.21582],
       ['5/27/2019', 8805.77832],
       ['5/28/2019', 8719.961914],
       ['5/29/2019', 8659.487305],
       ['5/30/2019', 8319.472656],
       ['5/31/2019', 8574.501953],
       ['6/1/2019', 8564.016602],
       ['6/2/2019', 8742.958008],
       ['6/3/2019', 8208.995117],
       ['6/4/2019', 7707.770995999999],
       ['6/5/2019', 7824.231445],
       ['6/6/2019', 7822.023437999999],
       ['6/7/2019', 8043.951172],
       ['6/8/2019', 7954.12793],
       ['6/9/2019', 7688.077148],
       ['6/10/2019', 8000.32959],
       ['6/11/2019', 7927.714355],
       ['6/12/2019', 8145.857422],
       ['6/13/2019', 8230.923828],
       ['6/14/2019', 8693.833008],
       ['6/15/2019', 8838.375],
       ['6/16/2019', 8994.488281],
       ['6/17/2019', 9320.352539],
       ['6/18/2019', 9081.762695],
       ['6/19/2019', 9273.521484],
       ['6/20/2019', 9527.160156],
       ['6/21/2019', 10144.55664],
       ['6/22/2019', 10701.69141],
       ['6/23/2019', 10855.37109],
       ['6/24/2019', 11011.10254],
       ['6/25/2019', 11790.91699],
       ['6/26/2019', 13016.23145],
       ['6/27/2019', 11182.80664],
       ['6/28/2019', 12407.33203],
       ['6/29/2019', 11959.37109],
       ['6/30/2019', 10817.155270000001],
       ['7/1/2019', 10583.13477],
       ['7/2/2019', 10801.67773],
       ['7/3/2019', 11961.26953],
       ['7/4/2019', 11215.4375],
       ['7/5/2019', 10978.45996],
       ['7/6/2019', 11208.55078],
       ['7/7/2019', 11450.84668],
       ['7/8/2019', 12285.95801],
       ['7/9/2019', 12573.8125],
       ['7/10/2019', 12156.5127],
       ['7/11/2019', 11358.66211],
       ['7/12/2019', 11815.98633],
       ['7/13/2019', 11392.37891],
       ['7/14/2019', 10256.05859],
       ['7/15/2019', 10895.08984],
       ['7/16/2019', 9477.641602],
       ['7/17/2019', 9693.802734],
       ['7/18/2019', 10666.48242],
       ['7/19/2019', 10530.73242],
       ['7/20/2019', 10767.13965],
       ['7/21/2019', 10599.10547],
       ['7/22/2019', 10343.10645],
       ['7/23/2019', 9900.767578],
       ['7/24/2019', 9811.925781],
       ['7/25/2019', 9911.841797],
       ['7/26/2019', 9870.303711],
       ['7/27/2019', 9477.677734],
       ['7/28/2019', 9552.860352],
       ['7/29/2019', 9519.145508],
       ['7/30/2019', 9607.423828],
       ['7/31/2019', 10085.62793],
       ['8/1/2019', 10399.66895],
       ['8/2/2019', 10518.174809999999],
       ['8/3/2019', 10821.72656],
       ['8/4/2019', 10970.18457],
       ['8/5/2019', 11805.65332],
       ['8/6/2019', 11478.16895],
       ['8/7/2019', 11941.96875],
       ['8/8/2019', 11966.407229999999],
       ['8/9/2019', 11862.936520000001],
       ['8/10/2019', 11354.02441],
       ['8/11/2019', 11523.5791],
       ['8/12/2019', 11382.61621],
       ['8/13/2019', 10895.83008],
       ['8/14/2019', 10051.7041],
       ['8/15/2019', 10311.5459],
       ['8/16/2019', 10374.33887],
       ['8/17/2019', 10231.74414],
       ['8/18/2019', 10345.81055],
       ['8/19/2019', 10916.05371],
       ['8/20/2019', 10763.23242],
       ['8/21/2019', 10138.049809999999],
       ['8/22/2019', 10131.05566],
       ['8/23/2019', 10407.96484],
       ['8/24/2019', 10159.96094],
       ['8/25/2019', 10138.51758],
       ['8/26/2019', 10370.82031],
       ['8/27/2019', 10185.5],
       ['8/28/2019', 9754.422852],
       ['8/29/2019', 9510.200195],
       ['8/30/2019', 9598.173828],
       ['8/31/2019', 9630.664063],
       ['9/1/2019', 9757.970703],
       ['9/2/2019', 10346.76074],
       ['9/3/2019', 10623.54004],
       ['9/4/2019', 10594.49316],
       ['9/5/2019', 10575.5332],
       ['9/6/2019', 10353.30273],
       ['9/7/2019', 10517.25488],
       ['9/8/2019', 10441.27637],
       ['9/9/2019', 10334.97461],
       ['9/10/2019', 10115.97559],
       ['9/11/2019', 10178.37207],
       ['9/12/2019', 10410.12695],
       ['9/13/2019', 10360.54688],
       ['9/14/2019', 10358.04883],
       ['9/15/2019', 10347.71289],
       ['9/16/2019', 10276.79395],
       ['9/17/2019', 10241.27246],
       ['9/18/2019', 10198.24805],
       ['9/19/2019', 10266.41504],
       ['9/20/2019', 10181.6416],
       ['9/21/2019', 10019.7168],
       ['9/22/2019', 10070.39258],
       ['9/23/2019', 9729.324219],
       ['9/24/2019', 8620.566406],
       ['9/25/2019', 8486.993164],
       ['9/26/2019', 8118.967773],
       ['9/27/2019', 8251.845703],
       ['9/28/2019', 8245.915039],
       ['9/29/2019', 8104.185547],
       ['9/30/2019', 8293.868164],
       ['10/1/2019', 8343.276367],
       ['10/2/2019', 8393.041992],
       ['10/3/2019', 8259.992188],
       ['10/4/2019', 8205.939453],
       ['10/5/2019', 8151.500488],
       ['10/6/2019', 7988.155762],
       ['10/7/2019', 8245.623047],
       ['10/8/2019', 8228.783203],
       ['10/9/2019', 8595.740234],
       ['10/10/2019', 8586.473633],
       ['10/11/2019', 8321.756836],
       ['10/12/2019', 8336.555664],
       ['10/13/2019', 8321.005859],
       ['10/14/2019', 8374.686523],
       ['10/15/2019', 8205.369141],
       ['10/16/2019', 8047.526855],
       ['10/17/2019', 8103.911133],
       ['10/18/2019', 7973.20752],
       ['10/19/2019', 7988.560547],
       ['10/20/2019', 8222.078125],
       ['10/21/2019', 8243.720703],
       ['10/22/2019', 8078.203125],
       ['10/23/2019', 7514.671875],
       ['10/24/2019', 7493.48877],
       ['10/25/2019', 8660.700195],
       ['10/26/2019', 9244.972656],
       ['10/27/2019', 9551.714844],
       ['10/28/2019', 9256.148438],
       ['10/29/2019', 9427.6875],
       ['10/30/2019', 9205.726563],
       ['10/31/2019', 9199.584961],
       ['11/1/2019', 9261.104492],
       ['11/2/2019', 9324.717773],
       ['11/3/2019', 9235.354492],
       ['11/4/2019', 9412.612305],
       ['11/5/2019', 9342.527344],
       ['11/6/2019', 9360.879883],
       ['11/7/2019', 9267.561523],
       ['11/8/2019', 8804.880859],
       ['11/9/2019', 8813.582031],
       ['11/10/2019', 9055.526367],
       ['11/11/2019', 8757.788086],
       ['11/12/2019', 8815.662109],
       ['11/13/2019', 8808.262695],
       ['11/14/2019', 8708.094727],
       ['11/15/2019', 8491.992188],
       ['11/16/2019', 8550.760742],
       ['11/17/2019', 8577.975586],
       ['11/18/2019', 8309.286133],
       ['11/19/2019', 8206.145508],
       ['11/20/2019', 8027.268066],
       ['11/21/2019', 7642.75],
       ['11/22/2019', 7296.577637],
       ['11/23/2019', 7397.796875],
       ['11/24/2019', 7047.916992],
       ['11/25/2019', 7146.133789],
       ['11/26/2019', 7218.371094],
       ['11/27/2019', 7531.663573999999],
       ['11/28/2019', 7463.105956999999],
       ['11/29/2019', 7761.243651999999],
       ['11/30/2019', 7569.629883],
       ['12/1/2019', 7424.29248],
       ['12/2/2019', 7321.988281],
       ['12/3/2019', 7320.145508],
       ['12/4/2019', 7252.034668000001],
       ['12/5/2019', 7448.307617],
       ['12/6/2019', 7546.996581999999],
       ['12/7/2019', 7556.237793000001],
       ['12/8/2019', 7564.345215],
       ['12/9/2019', 7400.899414],
       ['12/10/2019', 7278.119629000001],
       ['12/11/2019', 7217.427245999999],
       ['12/12/2019', 7243.134276999999],
       ['12/13/2019', 7269.68457],
       ['12/14/2019', 7124.673828],
       ['12/15/2019', 7152.301758],
       ['12/16/2019', 6932.480469],
       ['12/17/2019', 6640.515136999999],
       ['12/18/2019', 7276.802734000001],
       ['12/19/2019', 7202.844238],
       ['12/20/2019', 7218.816406],
       ['12/21/2019', 7191.158691],
       ['12/22/2019', 7511.588867],
       ['12/23/2019', 7355.628418000001],
       ['12/24/2019', 7322.532227],
       ['12/25/2019', 7275.155762],
       ['12/26/2019', 7238.966797],
       ['12/27/2019', 7290.088379000001],
       ['12/28/2019', 7317.990234000001],
       ['12/29/2019', 7422.652831999999],
       ['12/30/2019', 7292.995117],
       ['12/31/2019', 7193.599120999999],
       ['1/1/2020', 7200.174316],
       ['1/2/2020', 6985.470215],
       ['1/3/2020', 7344.884276999999],
       ['1/4/2020', 7410.656738],
       ['1/5/2020', 7411.317383],
       ['1/6/2020', 7769.219238],
       ['1/7/2020', 8163.692383],
       ['1/8/2020', 8079.862793000001],
       ['1/9/2020', 7879.071289],
       ['1/10/2020', 8166.554198999999],
       ['1/11/2020', 8037.537598000001],
       ['1/12/2020', 8192.494141],
       ['1/13/2020', 8144.194336],
       ['1/14/2020', 8827.764648],
       ['1/15/2020', 8807.010742],
       ['1/16/2020', 8723.786133],
       ['1/17/2020', 8929.038086],
       ['1/18/2020', 8942.808594],
       ['1/19/2020', 8706.245117],
       ['1/20/2020', 8657.642578],
       ['1/21/2020', 8745.894531],
       ['1/22/2020', 8680.875977],
       ['1/23/2020', 8406.515625],
       ['1/24/2020', 8445.43457],
       ['1/25/2020', 8367.847656],
       ['1/26/2020', 8596.830078],
       ['1/27/2020', 8909.819336],
       ['1/28/2020', 9358.589844],
       ['1/29/2020', 9316.629883],
       ['1/30/2020', 9508.993164],
       ['1/31/2020', 9350.529297],
       ['2/1/2020', 9392.875],
       ['2/2/2020', 9344.365234],
       ['2/3/2020', 9293.521484],
       ['2/4/2020', 9180.962891],
       ['2/5/2020', 9613.423828],
       ['2/6/2020', 9729.801758],
       ['2/7/2020', 9795.943359],
       ['2/8/2020', 9865.119141],
       ['2/9/2020', 10116.67383],
       ['2/10/2020', 9856.611328],
       ['2/11/2020', 10208.23633],
       ['2/12/2020', 10326.05469],
       ['2/13/2020', 10214.37988],
       ['2/14/2020', 10312.11621],
       ['2/15/2020', 9889.424805],
       ['2/16/2020', 9934.433594],
       ['2/17/2020', 9690.142578],
       ['2/18/2020', 10141.99609],
       ['2/19/2020', 9633.386719],
       ['2/20/2020', 9608.475586],
       ['2/21/2020', 9686.441406],
       ['2/22/2020', 9663.181641],
       ['2/23/2020', 9924.515625],
       ['2/24/2020', 9650.174805],
       ['2/25/2020', 9341.705078],
       ['2/26/2020', 8820.522461],
       ['2/27/2020', 8784.494141],
       ['2/28/2020', 8672.455078],
       ['2/29/2020', 8599.508789],
       ['3/1/2020', 8562.454102],
       ['3/2/2020', 8869.669922],
       ['3/3/2020', 8787.786133],
       ['3/4/2020', 8755.246094],
       ['3/5/2020', 9078.762695],
       ['3/6/2020', 9122.545898],
       ['3/7/2020', 8909.954102],
       ['3/8/2020', 8108.116211],
       ['3/9/2020', 7923.644531],
       ['3/10/2020', 7909.729492],
       ['3/11/2020', 7911.430176000001],
       ['3/12/2020', 4970.788086],
       ['3/13/2020', 5563.707031],
       ['3/14/2020', 5200.366211],
       ['3/15/2020', 5392.314941],
       ['3/16/2020', 5014.47998],
       ['3/17/2020', 5225.629395],
       ['3/18/2020', 5238.438477000001],
       ['3/19/2020', 6191.192871],
       ['3/20/2020', 6198.77832],
       ['3/21/2020', 6185.066406],
       ['3/22/2020', 5830.254883],
       ['3/23/2020', 6416.314941],
       ['3/24/2020', 6734.803711],
       ['3/25/2020', 6681.062988000001],
       ['3/26/2020', 6716.44043],
       ['3/27/2020', 6469.79834],
       ['3/28/2020', 6242.193848],
       ['3/29/2020', 5922.042969],
       ['3/30/2020', 6429.841797],
       ['3/31/2020', 6438.644531],
       ['4/1/2020', 6606.776367],
       ['4/2/2020', 6793.624512],
       ['4/3/2020', 6733.387206999999],
       ['4/4/2020', 6867.527344],
       ['4/5/2020', 6791.129395],
       ['4/6/2020', 7271.78125],
       ['4/7/2020', 7176.414551000001],
       ['4/8/2020', 7334.098633],
       ['4/9/2020', 7302.089355],
       ['4/10/2020', 6865.493164],
       ['4/11/2020', 6859.083008],
       ['4/12/2020', 6971.091797],
       ['4/13/2020', 6845.037598000001],
       ['4/14/2020', 6842.427734000001],
       ['4/15/2020', 6642.109863000001],
       ['4/16/2020', 7116.804198999999],
       ['4/17/2020', 7096.18457],
       ['4/18/2020', 7257.665039],
       ['4/19/2020', 7189.424805],
       ['4/20/2020', 6881.958495999999],
       ['4/21/2020', 6880.323242],
       ['4/22/2020', 7117.20752],
       ['4/23/2020', 7429.724609000001],
       ['4/24/2020', 7550.900879000001],
       ['4/25/2020', 7569.936035],
       ['4/26/2020', 7679.867187999999],
       ['4/27/2020', 7795.601073999999],
       ['4/28/2020', 7807.058594],
       ['4/29/2020', 8801.038086],
       ['4/30/2020', 8658.553711],
       ['5/1/2020', 8864.766602],
       ['5/2/2020', 8988.59668],
       ['5/3/2020', 8897.46875],
       ['5/4/2020', 8912.654297],
       ['5/5/2020', 9003.070313],
       ['5/6/2020', 9268.761719],
       ['5/7/2020', 9951.518555],
       ['5/8/2020', 9842.666016],
       ['5/9/2020', 9593.896484],
       ['5/10/2020', 8756.430664],
       ['5/11/2020', 8601.795898],
       ['5/12/2020', 8804.477539],
       ['5/13/2020', 9269.987305],
       ['5/14/2020', 9733.72168],
       ['5/15/2020', 9328.197266],
       ['5/16/2020', 9377.013672],
       ['5/17/2020', 9670.739258],
       ['5/18/2020', 9726.575195],
       ['5/19/2020', 9729.038086],
       ['5/20/2020', 9522.981445],
       ['5/21/2020', 9081.761719],
       ['5/22/2020', 9182.577148],
       ['5/23/2020', 9180.045898]], dtype=object)

In [9]:
df.count()

Date     367
Price    367
dtype: int64

In [65]:
df.describe()

              Price    Prediction
count    367.000000    337.000000
mean    8810.429461   8839.817226
std     1486.188684   1537.601784
min     4970.788086   4970.788086
25%     7661.308594   7531.663574
50%     8757.788086   8808.262695
75%     9867.711426   9951.518555
max    13016.231450  13016.231450

In [67]:
# i guess i will not be taking date into consideration so i will remove 
df.drop(["Date"],inplace=True,axis=1)
#once i use the function inplace = True that means it will be valid through entire notebook and changes will be permanent 
#axis= 1 signifies that particluar axis from where we are removing that is columns

KeyError: "['Date'] not found in axis"

In [62]:
#lets declare a vaiable called predictions so it basically means for how many days we are going to predict the bitcoin price 
predictionDays = 30
# Create another column shifted 'n'  units up
df['Prediction'] = df[['Price']].shift(-predictionDays)

In [63]:
df

           Price   Prediction
0    7881.846680  10701.69141
1    7987.371582  10855.37109
2    8052.543945  11011.10254
3    8673.215820  11790.91699
4    8805.778320  13016.23145
..           ...          ...
362  9729.038086          NaN
363  9522.981445          NaN
364  9081.761719          NaN
365  9182.577148          NaN
366  9180.045898          NaN

[367 rows x 2 columns]

In [64]:
df.tail()

           Price  Prediction
362  9729.038086         NaN
363  9522.981445         NaN
364  9081.761719         NaN
365  9182.577148         NaN
366  9180.045898         NaN

In [24]:
#now we will create the data set into an independent data set 
# we will convert the dataframe into numpy array 
x=np.array(df.drop(["Prediction"],axis=1))

In [25]:
print(x)

[[ 7881.84668 ]
 [ 7987.371582]
 [ 8052.543945]
 [ 8673.21582 ]
 [ 8805.77832 ]
 [ 8719.961914]
 [ 8659.487305]
 [ 8319.472656]
 [ 8574.501953]
 [ 8564.016602]
 [ 8742.958008]
 [ 8208.995117]
 [ 7707.770996]
 [ 7824.231445]
 [ 7822.023438]
 [ 8043.951172]
 [ 7954.12793 ]
 [ 7688.077148]
 [ 8000.32959 ]
 [ 7927.714355]
 [ 8145.857422]
 [ 8230.923828]
 [ 8693.833008]
 [ 8838.375   ]
 [ 8994.488281]
 [ 9320.352539]
 [ 9081.762695]
 [ 9273.521484]
 [ 9527.160156]
 [10144.55664 ]
 [10701.69141 ]
 [10855.37109 ]
 [11011.10254 ]
 [11790.91699 ]
 [13016.23145 ]
 [11182.80664 ]
 [12407.33203 ]
 [11959.37109 ]
 [10817.15527 ]
 [10583.13477 ]
 [10801.67773 ]
 [11961.26953 ]
 [11215.4375  ]
 [10978.45996 ]
 [11208.55078 ]
 [11450.84668 ]
 [12285.95801 ]
 [12573.8125  ]
 [12156.5127  ]
 [11358.66211 ]
 [11815.98633 ]
 [11392.37891 ]
 [10256.05859 ]
 [10895.08984 ]
 [ 9477.641602]
 [ 9693.802734]
 [10666.48242 ]
 [10530.73242 ]
 [10767.13965 ]
 [10599.10547 ]
 [10343.10645 ]
 [ 9900.767578]
 [ 9811.925781]
 [ 9911.841797]
 [ 9870.303711]
 [ 9477.677734]
 [ 9552.860352]
 [ 9519.145508]
 [ 9607.423828]
 [10085.62793 ]
 [10399.66895 ]
 [10518.17481 ]
 [10821.72656 ]
 [10970.18457 ]
 [11805.65332 ]
 [11478.16895 ]
 [11941.96875 ]
 [11966.40723 ]
 [11862.93652 ]
 [11354.02441 ]
 [11523.5791  ]
 [11382.61621 ]
 [10895.83008 ]
 [10051.7041  ]
 [10311.5459  ]
 [10374.33887 ]
 [10231.74414 ]
 [10345.81055 ]
 [10916.05371 ]
 [10763.23242 ]
 [10138.04981 ]
 [10131.05566 ]
 [10407.96484 ]
 [10159.96094 ]
 [10138.51758 ]
 [10370.82031 ]
 [10185.5     ]
 [ 9754.422852]
 [ 9510.200195]
 [ 9598.173828]
 [ 9630.664063]
 [ 9757.970703]
 [10346.76074 ]
 [10623.54004 ]
 [10594.49316 ]
 [10575.5332  ]
 [10353.30273 ]
 [10517.25488 ]
 [10441.27637 ]
 [10334.97461 ]
 [10115.97559 ]
 [10178.37207 ]
 [10410.12695 ]
 [10360.54688 ]
 [10358.04883 ]
 [10347.71289 ]
 [10276.79395 ]
 [10241.27246 ]
 [10198.24805 ]
 [10266.41504 ]
 [10181.6416  ]
 [10019.7168  ]
 [10070.39258 ]
 [ 9729.324219]
 [ 8620.566406]
 [ 8486.993164]
 [ 8118.967773]
 [ 8251.845703]
 [ 8245.915039]
 [ 8104.185547]
 [ 8293.868164]
 [ 8343.276367]
 [ 8393.041992]
 [ 8259.992188]
 [ 8205.939453]
 [ 8151.500488]
 [ 7988.155762]
 [ 8245.623047]
 [ 8228.783203]
 [ 8595.740234]
 [ 8586.473633]
 [ 8321.756836]
 [ 8336.555664]
 [ 8321.005859]
 [ 8374.686523]
 [ 8205.369141]
 [ 8047.526855]
 [ 8103.911133]
 [ 7973.20752 ]
 [ 7988.560547]
 [ 8222.078125]
 [ 8243.720703]
 [ 8078.203125]
 [ 7514.671875]
 [ 7493.48877 ]
 [ 8660.700195]
 [ 9244.972656]
 [ 9551.714844]
 [ 9256.148438]
 [ 9427.6875  ]
 [ 9205.726563]
 [ 9199.584961]
 [ 9261.104492]
 [ 9324.717773]
 [ 9235.354492]
 [ 9412.612305]
 [ 9342.527344]
 [ 9360.879883]
 [ 9267.561523]
 [ 8804.880859]
 [ 8813.582031]
 [ 9055.526367]
 [ 8757.788086]
 [ 8815.662109]
 [ 8808.262695]
 [ 8708.094727]
 [ 8491.992188]
 [ 8550.760742]
 [ 8577.975586]
 [ 8309.286133]
 [ 8206.145508]
 [ 8027.268066]
 [ 7642.75    ]
 [ 7296.577637]
 [ 7397.796875]
 [ 7047.916992]
 [ 7146.133789]
 [ 7218.371094]
 [ 7531.663574]
 [ 7463.105957]
 [ 7761.243652]
 [ 7569.629883]
 [ 7424.29248 ]
 [ 7321.988281]
 [ 7320.145508]
 [ 7252.034668]
 [ 7448.307617]
 [ 7546.996582]
 [ 7556.237793]
 [ 7564.345215]
 [ 7400.899414]
 [ 7278.119629]
 [ 7217.427246]
 [ 7243.134277]
 [ 7269.68457 ]
 [ 7124.673828]
 [ 7152.301758]
 [ 6932.480469]
 [ 6640.515137]
 [ 7276.802734]
 [ 7202.844238]
 [ 7218.816406]
 [ 7191.158691]
 [ 7511.588867]
 [ 7355.628418]
 [ 7322.532227]
 [ 7275.155762]
 [ 7238.966797]
 [ 7290.088379]
 [ 7317.990234]
 [ 7422.652832]
 [ 7292.995117]
 [ 7193.599121]
 [ 7200.174316]
 [ 6985.470215]
 [ 7344.884277]
 [ 7410.656738]
 [ 7411.317383]
 [ 7769.219238]
 [ 8163.692383]
 [ 8079.862793]
 [ 7879.071289]
 [ 8166.554199]
 [ 8037.537598]
 [ 8192.494141]
 [ 8144.194336]
 [ 8827.764648]
 [ 8807.010742]
 [ 8723.786133]
 [ 8929.038086]
 [ 8942.808594]
 [ 8706.245117]
 [ 8657.642578]
 [ 8745.894531]
 [ 8680.875977]
 [ 8406.515625]
 [ 8445.43457 ]
 [ 8367.847656]
 [ 8596.830078]
 [ 8909.819336]
 [ 9358.589844]
 [ 9316.629883]
 [ 9508.993164]
 [ 9350.529297]
 [ 9392.875   ]
 [ 9344.365234]
 [ 9293.521484]
 [ 9180.962891]
 [ 9613.423828]
 [ 9729.801758]
 [ 9795.943359]
 [ 9865.119141]
 [10116.67383 ]
 [ 9856.611328]
 [10208.23633 ]
 [10326.05469 ]
 [10214.37988 ]
 [10312.11621 ]
 [ 9889.424805]
 [ 9934.433594]
 [ 9690.142578]
 [10141.99609 ]
 [ 9633.386719]
 [ 9608.475586]
 [ 9686.441406]
 [ 9663.181641]
 [ 9924.515625]
 [ 9650.174805]
 [ 9341.705078]
 [ 8820.522461]
 [ 8784.494141]
 [ 8672.455078]
 [ 8599.508789]
 [ 8562.454102]
 [ 8869.669922]
 [ 8787.786133]
 [ 8755.246094]
 [ 9078.762695]
 [ 9122.545898]
 [ 8909.954102]
 [ 8108.116211]
 [ 7923.644531]
 [ 7909.729492]
 [ 7911.430176]
 [ 4970.788086]
 [ 5563.707031]
 [ 5200.366211]
 [ 5392.314941]
 [ 5014.47998 ]
 [ 5225.629395]
 [ 5238.438477]
 [ 6191.192871]
 [ 6198.77832 ]
 [ 6185.066406]
 [ 5830.254883]
 [ 6416.314941]
 [ 6734.803711]
 [ 6681.062988]
 [ 6716.44043 ]
 [ 6469.79834 ]
 [ 6242.193848]
 [ 5922.042969]
 [ 6429.841797]
 [ 6438.644531]
 [ 6606.776367]
 [ 6793.624512]
 [ 6733.387207]
 [ 6867.527344]
 [ 6791.129395]
 [ 7271.78125 ]
 [ 7176.414551]
 [ 7334.098633]
 [ 7302.089355]
 [ 6865.493164]
 [ 6859.083008]
 [ 6971.091797]
 [ 6845.037598]
 [ 6842.427734]
 [ 6642.109863]
 [ 7116.804199]
 [ 7096.18457 ]
 [ 7257.665039]
 [ 7189.424805]
 [ 6881.958496]
 [ 6880.323242]
 [ 7117.20752 ]
 [ 7429.724609]
 [ 7550.900879]
 [ 7569.936035]
 [ 7679.867188]
 [ 7795.601074]
 [ 7807.058594]
 [ 8801.038086]
 [ 8658.553711]
 [ 8864.766602]
 [ 8988.59668 ]
 [ 8897.46875 ]
 [ 8912.654297]
 [ 9003.070313]
 [ 9268.761719]
 [ 9951.518555]
 [ 9842.666016]
 [ 9593.896484]
 [ 8756.430664]
 [ 8601.795898]
 [ 8804.477539]
 [ 9269.987305]
 [ 9733.72168 ]
 [ 9328.197266]
 [ 9377.013672]
 [ 9670.739258]
 [ 9726.575195]
 [ 9729.038086]
 [ 9522.981445]
 [ 9081.761719]
 [ 9182.577148]
 [ 9180.045898]]

In [27]:
#now what we will do is that first we will remove the last n rows where n is the prediction days 
x=x[:len(df)-predictionDays]
print(x)

[[ 7881.84668 ]
 [ 7987.371582]
 [ 8052.543945]
 [ 8673.21582 ]
 [ 8805.77832 ]
 [ 8719.961914]
 [ 8659.487305]
 [ 8319.472656]
 [ 8574.501953]
 [ 8564.016602]
 [ 8742.958008]
 [ 8208.995117]
 [ 7707.770996]
 [ 7824.231445]
 [ 7822.023438]
 [ 8043.951172]
 [ 7954.12793 ]
 [ 7688.077148]
 [ 8000.32959 ]
 [ 7927.714355]
 [ 8145.857422]
 [ 8230.923828]
 [ 8693.833008]
 [ 8838.375   ]
 [ 8994.488281]
 [ 9320.352539]
 [ 9081.762695]
 [ 9273.521484]
 [ 9527.160156]
 [10144.55664 ]
 [10701.69141 ]
 [10855.37109 ]
 [11011.10254 ]
 [11790.91699 ]
 [13016.23145 ]
 [11182.80664 ]
 [12407.33203 ]
 [11959.37109 ]
 [10817.15527 ]
 [10583.13477 ]
 [10801.67773 ]
 [11961.26953 ]
 [11215.4375  ]
 [10978.45996 ]
 [11208.55078 ]
 [11450.84668 ]
 [12285.95801 ]
 [12573.8125  ]
 [12156.5127  ]
 [11358.66211 ]
 [11815.98633 ]
 [11392.37891 ]
 [10256.05859 ]
 [10895.08984 ]
 [ 9477.641602]
 [ 9693.802734]
 [10666.48242 ]
 [10530.73242 ]
 [10767.13965 ]
 [10599.10547 ]
 [10343.10645 ]
 [ 9900.767578]
 [ 9811.925781]
 [ 9911.841797]
 [ 9870.303711]
 [ 9477.677734]
 [ 9552.860352]
 [ 9519.145508]
 [ 9607.423828]
 [10085.62793 ]
 [10399.66895 ]
 [10518.17481 ]
 [10821.72656 ]
 [10970.18457 ]
 [11805.65332 ]
 [11478.16895 ]
 [11941.96875 ]
 [11966.40723 ]
 [11862.93652 ]
 [11354.02441 ]
 [11523.5791  ]
 [11382.61621 ]
 [10895.83008 ]
 [10051.7041  ]
 [10311.5459  ]
 [10374.33887 ]
 [10231.74414 ]
 [10345.81055 ]
 [10916.05371 ]
 [10763.23242 ]
 [10138.04981 ]
 [10131.05566 ]
 [10407.96484 ]
 [10159.96094 ]
 [10138.51758 ]
 [10370.82031 ]
 [10185.5     ]
 [ 9754.422852]
 [ 9510.200195]
 [ 9598.173828]
 [ 9630.664063]
 [ 9757.970703]
 [10346.76074 ]
 [10623.54004 ]
 [10594.49316 ]
 [10575.5332  ]
 [10353.30273 ]
 [10517.25488 ]
 [10441.27637 ]
 [10334.97461 ]
 [10115.97559 ]
 [10178.37207 ]
 [10410.12695 ]
 [10360.54688 ]
 [10358.04883 ]
 [10347.71289 ]
 [10276.79395 ]
 [10241.27246 ]
 [10198.24805 ]
 [10266.41504 ]
 [10181.6416  ]
 [10019.7168  ]
 [10070.39258 ]
 [ 9729.324219]
 [ 8620.566406]
 [ 8486.993164]
 [ 8118.967773]
 [ 8251.845703]
 [ 8245.915039]
 [ 8104.185547]
 [ 8293.868164]
 [ 8343.276367]
 [ 8393.041992]
 [ 8259.992188]
 [ 8205.939453]
 [ 8151.500488]
 [ 7988.155762]
 [ 8245.623047]
 [ 8228.783203]
 [ 8595.740234]
 [ 8586.473633]
 [ 8321.756836]
 [ 8336.555664]
 [ 8321.005859]
 [ 8374.686523]
 [ 8205.369141]
 [ 8047.526855]
 [ 8103.911133]
 [ 7973.20752 ]
 [ 7988.560547]
 [ 8222.078125]
 [ 8243.720703]
 [ 8078.203125]
 [ 7514.671875]
 [ 7493.48877 ]
 [ 8660.700195]
 [ 9244.972656]
 [ 9551.714844]
 [ 9256.148438]
 [ 9427.6875  ]
 [ 9205.726563]
 [ 9199.584961]
 [ 9261.104492]
 [ 9324.717773]
 [ 9235.354492]
 [ 9412.612305]
 [ 9342.527344]
 [ 9360.879883]
 [ 9267.561523]
 [ 8804.880859]
 [ 8813.582031]
 [ 9055.526367]
 [ 8757.788086]
 [ 8815.662109]
 [ 8808.262695]
 [ 8708.094727]
 [ 8491.992188]
 [ 8550.760742]
 [ 8577.975586]
 [ 8309.286133]
 [ 8206.145508]
 [ 8027.268066]
 [ 7642.75    ]
 [ 7296.577637]
 [ 7397.796875]
 [ 7047.916992]
 [ 7146.133789]
 [ 7218.371094]
 [ 7531.663574]
 [ 7463.105957]
 [ 7761.243652]
 [ 7569.629883]
 [ 7424.29248 ]
 [ 7321.988281]
 [ 7320.145508]
 [ 7252.034668]
 [ 7448.307617]
 [ 7546.996582]
 [ 7556.237793]
 [ 7564.345215]
 [ 7400.899414]
 [ 7278.119629]
 [ 7217.427246]
 [ 7243.134277]
 [ 7269.68457 ]
 [ 7124.673828]
 [ 7152.301758]
 [ 6932.480469]
 [ 6640.515137]
 [ 7276.802734]
 [ 7202.844238]
 [ 7218.816406]
 [ 7191.158691]
 [ 7511.588867]
 [ 7355.628418]
 [ 7322.532227]
 [ 7275.155762]
 [ 7238.966797]
 [ 7290.088379]
 [ 7317.990234]
 [ 7422.652832]
 [ 7292.995117]
 [ 7193.599121]
 [ 7200.174316]
 [ 6985.470215]
 [ 7344.884277]
 [ 7410.656738]
 [ 7411.317383]
 [ 7769.219238]
 [ 8163.692383]
 [ 8079.862793]
 [ 7879.071289]
 [ 8166.554199]
 [ 8037.537598]
 [ 8192.494141]
 [ 8144.194336]
 [ 8827.764648]
 [ 8807.010742]
 [ 8723.786133]
 [ 8929.038086]
 [ 8942.808594]
 [ 8706.245117]
 [ 8657.642578]
 [ 8745.894531]
 [ 8680.875977]
 [ 8406.515625]
 [ 8445.43457 ]
 [ 8367.847656]
 [ 8596.830078]
 [ 8909.819336]
 [ 9358.589844]
 [ 9316.629883]
 [ 9508.993164]
 [ 9350.529297]
 [ 9392.875   ]
 [ 9344.365234]
 [ 9293.521484]
 [ 9180.962891]
 [ 9613.423828]
 [ 9729.801758]
 [ 9795.943359]
 [ 9865.119141]
 [10116.67383 ]
 [ 9856.611328]
 [10208.23633 ]
 [10326.05469 ]
 [10214.37988 ]
 [10312.11621 ]
 [ 9889.424805]
 [ 9934.433594]
 [ 9690.142578]
 [10141.99609 ]
 [ 9633.386719]
 [ 9608.475586]
 [ 9686.441406]
 [ 9663.181641]
 [ 9924.515625]
 [ 9650.174805]
 [ 9341.705078]
 [ 8820.522461]
 [ 8784.494141]
 [ 8672.455078]
 [ 8599.508789]
 [ 8562.454102]
 [ 8869.669922]
 [ 8787.786133]
 [ 8755.246094]
 [ 9078.762695]
 [ 9122.545898]
 [ 8909.954102]
 [ 8108.116211]
 [ 7923.644531]
 [ 7909.729492]
 [ 7911.430176]
 [ 4970.788086]
 [ 5563.707031]
 [ 5200.366211]
 [ 5392.314941]
 [ 5014.47998 ]
 [ 5225.629395]
 [ 5238.438477]
 [ 6191.192871]
 [ 6198.77832 ]
 [ 6185.066406]
 [ 5830.254883]
 [ 6416.314941]
 [ 6734.803711]
 [ 6681.062988]
 [ 6716.44043 ]
 [ 6469.79834 ]
 [ 6242.193848]
 [ 5922.042969]
 [ 6429.841797]
 [ 6438.644531]
 [ 6606.776367]
 [ 6793.624512]
 [ 6733.387207]
 [ 6867.527344]
 [ 6791.129395]
 [ 7271.78125 ]
 [ 7176.414551]
 [ 7334.098633]
 [ 7302.089355]
 [ 6865.493164]
 [ 6859.083008]
 [ 6971.091797]
 [ 6845.037598]
 [ 6842.427734]
 [ 6642.109863]
 [ 7116.804199]
 [ 7096.18457 ]
 [ 7257.665039]
 [ 7189.424805]
 [ 6881.958496]
 [ 6880.323242]
 [ 7117.20752 ]
 [ 7429.724609]]

In [31]:
y=np.array(df["Prediction"])

y=y[:-predictionDays]
print(y)

[10701.69141  10855.37109  11011.10254  11790.91699  13016.23145
 11182.80664  12407.33203  11959.37109  10817.15527  10583.13477
 10801.67773  11961.26953  11215.4375   10978.45996  11208.55078
 11450.84668  12285.95801  12573.8125   12156.5127   11358.66211
 11815.98633  11392.37891  10256.05859  10895.08984   9477.641602
  9693.802734 10666.48242  10530.73242  10767.13965  10599.10547
 10343.10645   9900.767578  9811.925781  9911.841797  9870.303711
  9477.677734  9552.860352  9519.145508  9607.423828 10085.62793
 10399.66895  10518.17481  10821.72656  10970.18457  11805.65332
 11478.16895  11941.96875  11966.40723  11862.93652  11354.02441
 11523.5791   11382.61621  10895.83008  10051.7041   10311.5459
 10374.33887  10231.74414  10345.81055  10916.05371  10763.23242
 10138.04981  10131.05566  10407.96484  10159.96094  10138.51758
 10370.82031  10185.5       9754.422852  9510.200195  9598.173828
  9630.664063  9757.970703 10346.76074  10623.54004  10594.49316
 10575.5332   10353.30273  10517.25488  10441.27637  10334.97461
 10115.97559  10178.37207  10410.12695  10360.54688  10358.04883
 10347.71289  10276.79395  10241.27246  10198.24805  10266.41504
 10181.6416   10019.7168   10070.39258   9729.324219  8620.566406
  8486.993164  8118.967773  8251.845703  8245.915039  8104.185547
  8293.868164  8343.276367  8393.041992  8259.992188  8205.939453
  8151.500488  7988.155762  8245.623047  8228.783203  8595.740234
  8586.473633  8321.756836  8336.555664  8321.005859  8374.686523
  8205.369141  8047.526855  8103.911133  7973.20752   7988.560547
  8222.078125  8243.720703  8078.203125  7514.671875  7493.48877
  8660.700195  9244.972656  9551.714844  9256.148438  9427.6875
  9205.726563  9199.584961  9261.104492  9324.717773  9235.354492
  9412.612305  9342.527344  9360.879883  9267.561523  8804.880859
  8813.582031  9055.526367  8757.788086  8815.662109  8808.262695
  8708.094727  8491.992188  8550.760742  8577.975586  8309.286133
  8206.145508  8027.268066  7642.75      7296.577637  7397.796875
  7047.916992  7146.133789  7218.371094  7531.663574  7463.105957
  7761.243652  7569.629883  7424.29248   7321.988281  7320.145508
  7252.034668  7448.307617  7546.996582  7556.237793  7564.345215
  7400.899414  7278.119629  7217.427246  7243.134277  7269.68457
  7124.673828  7152.301758  6932.480469  6640.515137  7276.802734
  7202.844238  7218.816406  7191.158691  7511.588867  7355.628418
  7322.532227  7275.155762  7238.966797  7290.088379  7317.990234
  7422.652832  7292.995117  7193.599121  7200.174316  6985.470215
  7344.884277  7410.656738  7411.317383  7769.219238  8163.692383
  8079.862793  7879.071289  8166.554199  8037.537598  8192.494141
  8144.194336  8827.764648  8807.010742  8723.786133  8929.038086
  8942.808594  8706.245117  8657.642578  8745.894531  8680.875977
  8406.515625  8445.43457   8367.847656  8596.830078  8909.819336
  9358.589844  9316.629883  9508.993164  9350.529297  9392.875
  9344.365234  9293.521484  9180.962891  9613.423828  9729.801758
  9795.943359  9865.119141 10116.67383   9856.611328 10208.23633
 10326.05469  10214.37988  10312.11621   9889.424805  9934.433594
  9690.142578 10141.99609   9633.386719  9608.475586  9686.441406
  9663.181641  9924.515625  9650.174805  9341.705078  8820.522461
  8784.494141  8672.455078  8599.508789  8562.454102  8869.669922
  8787.786133  8755.246094  9078.762695  9122.545898  8909.954102
  8108.116211  7923.644531  7909.729492  7911.430176  4970.788086
  5563.707031  5200.366211  5392.314941  5014.47998   5225.629395
  5238.438477  6191.192871  6198.77832   6185.066406  5830.254883
  6416.314941  6734.803711  6681.062988  6716.44043   6469.79834
  6242.193848  5922.042969  6429.841797  6438.644531  6606.776367
  6793.624512  6733.387207  6867.527344  6791.129395  7271.78125
  7176.414551  7334.098633  7302.089355  6865.493164  6859.083008
  6971.091797  6845.037598  6842.427734  6642.109863  7116.804199
  7096.18457   7257.665039  7189.424805  6881.958496  6880.323242
  7117.20752   7429.724609  7550.900879  7569.936035  7679.867188
  7795.601074  7807.058594  8801.038086  8658.553711  8864.766602
  8988.59668   8897.46875   8912.654297  9003.070313  9268.761719
  9951.518555  9842.666016  9593.896484  8756.430664  8601.795898
  8804.477539  9269.987305  9733.72168   9328.197266  9377.013672
  9670.739258  9726.575195  9729.038086  9522.981445  9081.761719
  9182.577148  9180.045898]

In [35]:
#spliting the data inot training data and testing data 
from sklearn.model_selection import train_test_split

In [38]:
 x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [39]:
predictionDays_array = np.array(df.drop(['Prediction'],1))[-predictionDays:]
print(predictionDays_array)

[[7550.900879]
 [7569.936035]
 [7679.867188]
 [7795.601074]
 [7807.058594]
 [8801.038086]
 [8658.553711]
 [8864.766602]
 [8988.59668 ]
 [8897.46875 ]
 [8912.654297]
 [9003.070313]
 [9268.761719]
 [9951.518555]
 [9842.666016]
 [9593.896484]
 [8756.430664]
 [8601.795898]
 [8804.477539]
 [9269.987305]
 [9733.72168 ]
 [9328.197266]
 [9377.013672]
 [9670.739258]
 [9726.575195]
 [9729.038086]
 [9522.981445]
 [9081.761719]
 [9182.577148]
 [9180.045898]]

In [53]:
from sklearn.svm import SVR
model=SVR(C=1000.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=1e-05,
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)
model.fit(x_train,y_train)

SVR(C=1000.0, gamma=1e-05)

In [54]:
model.predict(x_test)

array([ 9201.95992314,  7937.59309236, 10403.72916627,  8032.80484124,
        9809.9295725 ,  9202.28745163,  9463.19857888,  8503.77002749,
        8242.3153504 ,  8632.2369395 ,  9377.74236306,  9377.12575196,
        8125.8607841 ,  8396.99892358,  9321.78835145,  9346.79019247,
        8204.063458  ,  8794.75048372,  9278.42350664,  8236.20846073,
        8648.45436084, 10327.42127979,  8155.27217895,  8006.03941291,
        9834.51145852,  9863.95083292,  8636.95657843,  8201.47675068,
        7261.75372408, 10078.8830095 ,  9170.69002355, 10402.10215538,
        8180.41969158,  7906.84848995,  8063.4766206 ,  9223.88299573,
        8254.06383031,  8348.36207711, 10314.27191487,  9284.86054012,
        9607.56708073,  9642.23949545,  9265.93430245,  8231.88923006,
        9500.60649989,  8203.97412951,  9837.85771968,  7640.91762067,
        9460.677593  ,  8576.56409224,  9555.77498217,  9207.06843157,
        8420.35120585,  9571.36677716, 10411.2704403 ,  7621.50372259,
        9185.49511962,  9205.93881842,  9343.88359661,  8233.50870184,
        9378.79290159,  7973.9333074 ,  9218.73513652, 10182.96228775,
        8602.17680717,  9297.89274885,  8439.01385233,  8819.99589451])

In [55]:
print(y_test)

[ 9055.526367  6867.527344  9900.767578  8801.038086  7334.098633
 11959.37109   8245.623047  6416.314941  7252.034668 10767.13965
  7047.916992  9633.386719 10131.05566   8205.369141  9244.972656
  9427.6875    8163.692383  8367.847656  9412.612305  8620.566406
  9268.761719 11354.02441   5225.629395  8745.894531  7302.089355
 10701.69141   8104.185547  8222.078125  7807.058594  8259.992188
  8807.010742 10346.76074   8103.911133  8787.786133  7290.088379
 11392.37891   8680.875977  8595.740234 10343.10645  11815.98633
 12156.5127    8309.286133  9729.801758  7292.995117  9856.611328
  8321.756836  8151.500488 10530.73242  11011.10254   6198.77832
 10345.81055  13016.23145   7988.155762  7422.652832 10198.24805
  6971.091797  7400.899414  8804.477539  6429.841797  6191.192871
  5922.042969  7397.796875  9360.879883 11478.16895   8245.915039
  6932.480469  5830.254883  7271.78125 ]

In [56]:
accuracy_score=model.score(x_test,y_test)

In [57]:
accuracy_score

0.14418305361937878

In [58]:
# Print the model predictions for the next 30 days
svm_prediction = model.predict(predictionDays_array)
print(svm_prediction)
print()
#Print the actual price for bitcoin for last 30 days
print(df.tail(predictionDays))

[8139.46384887 8233.54169929 9013.65261444 9730.20403397 9769.92350047
 9219.54405777 9377.32380116 9013.07720831 8416.99017543 8876.80277642
 8807.39085155 8337.77352515 7629.15030203 8173.82387055 8118.48755526
 8641.83578894 9313.40238729 9345.7922521  9210.53935521 7632.0925441
 8304.83995381 7833.90724936 8065.79967441 8483.23968691 8324.3553976
 8317.57420953 8625.88251959 7923.17397391 7588.18981648 7592.02399762]

           Price  Prediction
337  7550.900879         NaN
338  7569.936035         NaN
339  7679.867188         NaN
340  7795.601074         NaN
341  7807.058594         NaN
342  8801.038086         NaN
343  8658.553711         NaN
344  8864.766602         NaN
345  8988.596680         NaN
346  8897.468750         NaN
347  8912.654297         NaN
348  9003.070313         NaN
349  9268.761719         NaN
350  9951.518555         NaN
351  9842.666016         NaN
352  9593.896484         NaN
353  8756.430664         NaN
354  8601.795898         NaN
355  8804.477539         NaN
356  9269.987305         NaN
357  9733.721680         NaN
358  9328.197266         NaN
359  9377.013672         NaN
360  9670.739258         NaN
361  9726.575195         NaN
362  9729.038086         NaN
363  9522.981445         NaN
364  9081.761719         NaN
365  9182.577148         NaN
366  9180.045898         NaN